// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestService.DataAccess;

#nullable disable

namespace TestService.Migrations
{
    [DbContext(typeof(UnitContext))]
    [Migration("20220406225333_AddUnit")]
    partial class AddUnit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestService.DataAccess.Entity.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MainId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MainId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("TestService.DataAccess.Entity.Unit", b =>
                {
                    b.HasOne("TestService.DataAccess.Entity.Unit", "MainUnit")
                        .WithMany("SubUnits")
                        .HasForeignKey("MainId");

                    b.Navigation("MainUnit");
                });

            modelBuilder.Entity("TestService.DataAccess.Entity.Unit", b =>
                {
                    b.Navigation("SubUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
